version: '3'

services:
  web:
    image: php:7.4-apache
    volumes:
      - ./web:/var/www/html
    ports:
      - "8081:80"
    networks:
      - php-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8090:80"
    networks:
      - php-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=bestpractice
      - MYSQL_USER=root
      - MYSQL_PASSWORD=db_password
    networks:
      - php-network

networks:
  php-network:
