version: "3"

services:
    www:
        build: .
        ports:
            - "7000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - web-networks
    db:
        image: mysql:8.2.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bestpractice
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345678
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./slq:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - web-networks
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "7070:80"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345678
            MYSQL_ROOT_PASSWORD: 12345678

volumes:
    persistent:
