version: "3"
services:
    www:
        build: .
        ports:
            - "7000:70"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "7070:70"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: save
            MYSQL_ROOT_PASSWORD: save
volumes:
    persistent:

