---
version: "3"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bestpractice
            MYSQL_USER: root
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
volumes:
     - /var/run/docker.sock:/var/run/docker.sock