version: "3"

services:
    www:
        build: .
        ports:
            - "7070:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - web-server
            
    db:
        image: mysql:5.7
        container_name: db
        environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: bestpractice
        MYSQL_USER: root
        MYSQL_PASSWORD: save12345678
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - web-server

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
        networks:
            - web-server
            
volumes:
     persistent:

networks:
    web-server:
        driver: bridge
