version: "3"
services:
    www:
        build: .
        ports:
            - "7000:7000"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - 172.26.0.2
    db:
        image: mysql:8.2.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bestpractice
            MYSQL_USER: root
            MYSQL_PASSWORD: save
            MYSQL_ROOT_PASSWORD: save
        volumes:
            - ./slq:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - 172.26.0.2
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "7070:7070"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: save
            MYSQL_ROOT_PASSWORD: save
        volumes:
            persistent:
