version: "3"

services:

    db:
        image: jsurf/rpi-mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        restart: always

        volumes:
            - db:/var/lib/mysql
        env_file:
            - pi.env

    nextcloud:
        image: nextcloud:apache
        restart: always
        container_name: nextcloud
        volumes: 
            - www:/var/www/html
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
            - MYSQL_HOST=db
            - NEXTCLOUD_TRUSTED_DOMAINS=${VIRTUAL_HOST}
            - NEXTCLOUD_TRUSTED_DOMAINS=proxy
        env_file:
            - pi.env
        depends_on:
            - db
        networks:
            - mynetwork


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        hostname: phpmyadmin
        ports:
            - 8090:80
        environment:
            - PMA_HOST=db
        networks:
            - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
    persistent:
