version: "3"
services:
    www:
        build: .
        ports:
            - "7000:7000"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bestpractice
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - ./slq:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "7270:7270"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
volumes:
    persistent:

