version: "3"

services:

    db:
        image: mariadb
        env_file:
        - pi.env
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        restart: always
        volumes:
        - db:/var/lib/mysql
        networks:
            - mynetwork

    nextcloud:
        image: nextcloud:apache
        env_file:
            - pi.env
        restart: always
        ports:
             - 8081:80
        volumes: 
            - www:/var/www/html
        depends_on:
            - db
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_USER=phpmyadmin
            - MYSQL_PASSWORD=P@ssword
            - MYSQL_ROOT_PASSWORD
        networks:
            - mynetwork


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        hostname: phpmyadmin
        ports:
            - 8090:80
        environment:
            - PMA_HOST=db
        networks:
            - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
    persistent:
