version: "3"

services:
    mariadb:
        image: mariadb:10
        hostname: mariadb
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./schema:/docker-entrypoint-initdb.d
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=123456
            - "MYSQL_ROOT_HOST=%"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        hostname: phpmyadmin
        ports:
            - 8090:80
        environment:
            - PMA_HOST=mariadb
    www:
        build: .
        ports:
            - "8070:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mariadb
        networks:
            - web-server
            

networks:
    web-server:
        driver: bridge

volumes:
    persistent:
