version: "3"

services:
    mariadb:
        image: mariadb:10
        hostname: mariadb
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./schema:/docker-entrypoint-initdb.d
        environment:
            - TZ=Asia/Bangkok
            - MYSQL_ROOT_PASSWORD=12345678
            - "MYSQL_ROOT_HOST=%"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        hostname: phpmyadmin
        ports:
            - 8090:80
        environment:
            - PMA_HOST=mariadb
    webserver:
        image: nginx:latest  # หรือเลือกเซิร์ฟเวอร์ที่คุณต้องการใช้
        ports:
            - 8070:80
        volumes:
            - ./www:/var/www/html  # เปลี่ยนตามโครงสร้างโฟลเดอร์ของคุณ
        depends_on:
            - php
        networks:
            - mynetwork

    php:
        image: php:latest  # หรือเลือกเวอร์ชันที่คุณต้องการใช้
        volumes:
            - ./www:/var/www/html  # เปลี่ยนตามโครงสร้างโฟลเดอร์ของคุณ
        depends_on:
            - mariadb
        networks:
            - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
    persistent:
