version: "3"

services:
    www:
        build: .
        ports:
            - "8090:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - web-server
            
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        networks:
            - web-server

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8081:80"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root1234
            MYSQL_ROOT_PASSWORD: root1234

networks:
    web-server:
        driver: bridge

volumes:
    persistent:
