version: "3"

services:
    www:
        build: .
        ports:
            - "8090:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - web-server
            
    mariadb:
    image: mariadb:10
    hostname: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=12345678
      - "MYSQL_ROOT_HOST=%"

networks:
    web-server:
        driver: bridge

volumes:
    persistent:
