version: "3"

services:
    www:
        build: .
        ports:
            - "7000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - web-server
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: bestpractice
            MYSQL_USER: root
            MYSQL_PASSWORD: save12345678
        ports:
            - "3306:3306"
        networks:
            - web-server
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "7070:80"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: save12345678
            MYSQL_ROOT_PASSWORD: save12345678

networks:
    web-server:
        driver: bridge

volumes:
    persistent:
